# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'mxyc_set' do
  pod 'Masonry', '~> 1.0.0'

  target 'mxyc_setTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mxyc_setUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
